### ISSUE TITLE
How to print multi svgs in one piece of A4 paper?

### ISSUE THREAD

**Issue by ELFEamp** [SabinT/musicbox-svg#1]
hello, I appreciate that you construct this incredible repo since it helps me a lot with midi conversion. But I found that the paper stripe segments are arranged into different svgs, and it is wasted to print one svg only in a piece of A4 paper. Is there any way to gather several svgs in the same paper?

**Comment by SabinT** [comment]
I believe this is resolved now. There should be pagination options to control the page width/height in mm and should fit as many strips as possible in every page.
